import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Button } from "@/presentation/components/ui/Button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col selection:bg-primary/30 selection:text-white">
        <header className="fixed top-0 w-full z-50 glass border-b-white/5">
          <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center font-bold text-slate-900">P</div>
              <span className="text-xl font-bold tracking-tight text-white">Peladeiros<span className="text-primary">.Pro</span></span>
            </div>
            <nav className="hidden md:flex items-center gap-8">
              <Link href="/dashboard/matches" className="text-sm font-medium text-white/60 hover:text-primary transition-colors animated-underline">Partidas</Link>
              <Link href="/dashboard/players" className="text-sm font-medium text-white/60 hover:text-primary transition-colors animated-underline">Grupos</Link>
              <Link href="/dashboard/stats" className="text-sm font-medium text-white/60 hover:text-primary transition-colors animated-underline">Ranking</Link>
            </nav>
            <div className="flex items-center gap-4">
              <Link href="/dashboard" className="text-sm font-medium text-white/60 hover:text-white transition-colors">Entrar</Link>
              <Button href="/dashboard" className="bg-primary text-slate-900 px-4 py-2 rounded-lg text-sm font-bold hover:brightness-110 transition-all">Começar Agora</Button>
            </div>
          </div>
        </header>
        <main className="flex-1 pt-16">
          {children}
        </main>
        <footer className="py-12 border-t border-white/5 bg-slate-950/50">
          <div className="max-w-7xl mx-auto px-6 text-center">
            <p className="text-sm text-white/40">&copy; 2026 Peladeiros Pro. Todos os direitos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
